---
- name: Look for mysql 5.6
  shell: "dpkg -s mysql-server"
  ignore_errors: yes
  register: mysql_56_installed
  changed_when: no

- name: Important message
  debug:
    msg: |
      "MySQL experimental is already installed, make 'remove_experimental_mysql: true' in defaults/main.yml, 
      if you want to remove it and install the stable version of MySQL"
  when: "'5.6.14' in  mysql_56_installed.stdout and not remove_experimental_mysql"

- pause:
    seconds: 10
  when: "'5.6.14' in  mysql_56_installed.stdout and not remove_experimental_mysql"

# remove this, once the new devstack is out
- include: remove_mysql_experimental.yml
  when: remove_experimental_mysql

- include: mysql.yml
  when: (mysql_56_installed.rc == 1) or (remove_experimental_mysql)

- name: Copy the my.cnf file 
  template: src=my.cnf.{{ ansible_os_family }}.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify: 
   - restart mysql

- name: Create the directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify:
   - restart mysql

- name: Start the mysql services
  service: name={{ mysql_service }} state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost' 

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost' 

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: Ensure Anonymous user(s) does not exist
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent
