---

- name: Add MySQL community apt key
  apt_key:
    id: 8C718D3B5072E1F5
    keyserver: "{{ XJHORSE_MYSQL_PPA_KEY_SERVER }}"
    state: present

- name: Install MySQL community apt repositories
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6"
    update_cache: yes

- name: Install mysql-5.6 and dependencies
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present
  with_items: "{{ mysql_debian_pkgs }}"

- name: Start mysql
  service:
    name: mysql
    state: started
