---

# 安装xjhorse数据库的sandbox配置文件

- name: Configure instance(s)
  hosts: datastores
  become: True
  gather_facts: True

  vars_files:
    - "vars.yml"
  roles:
    # 安装memcached服务器
    - role: memcache

    # 安装mysql服务器、创建数据库及用户
    - role: datastore