---

# xjhorse门户服务器安装沙盒，使用外部的mysql, memcached

- name: Configure instance(s)
  hosts: xjhorse
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    NGINX_PORT: '80'
    platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True

  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: nginx
    - role: edxlocal
      when: MYSQL_HOST == 'localhost'
    - role: memcache
      when: "'localhost' in ' '.join(MEMCACHE)"
    - role: mongo
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - edx_ansible
