---

# xjhorse门户服务器安装沙盒，使用外部的mysql, memcached

- name: Configure instance(s)
  hosts: xjhorse
  sudo: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    openid_workaround: True
    XJHORSE_NGINX_PORT: '80'
    XJHORSE_MYSQL_HOST: "{{ groups['datastores'][0] }}"
    XJHORSE_MEMCACHE: ["{{ groups['datastores'][0] }}:11211"]

  roles:

    # 服务器虚拟内存交换文件大小
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }

    # nginx反向代理
    - role: nginx
      nginx_sites:
      - xjhorse
      nginx_default_sites:
      - xjhorse

    # Xjhorse主App
    # https://github.com/edx/edx-platform
    - role: xjhorseapp
      celery_worker: True
    - xjhorseapp
    - ansible
